name       : sayonara-player
version    : 1.0.0
release    : 4
source     :
    - http://sayonara-player.com/sw/sayonara-player-1.0.0-git5-20180115.tar.gz : 673ccc89892261293d4400d5b5651a521ad2ee42643c527bd86be76ce9fd87ba
license    : GPL-3.0
component  : multimedia.audio
summary    : A small, clear and fast audio player for Linux
description: |
    Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt
    framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=true
build      : |
    %make
install    : |
    %make_install
