name       : sayonara-player
version    : 1.4.1
release    : 7
source     :
    - https://sayonara-player.com/sw/sayonara-player-1.4.1-stable1.tar.gz : d610264b52e8a47ac97a9009a6eff73e28b0b7fe48c12cf83fd174313723c445
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small and fast audio player built with Qt
description: |
    Sayonara is a small, clear and fast audio player written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
