name       : sayonara-player
version    : 0.9.2
release    : 1
source     :
    - https://sayonara-player.com/sw/sayonara-player-0.9.2-git11-20161030.tar.gz : 815c2e0c64520edb99571b52c6384320c110e8a4ef5be5c13803a156f64be148
license    : GPL-3.0
component  : multimedia.audio
summary    : A small, clear and fast audio player for Linux
description: |
    Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt
    framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(taglib)
setup      : |
    find . -name "CMakeFiles.txt" -exec sed -e "s:STATIC:SHARED:g" -i {} \;
    %cmake .
build      : |
    %make
install    : |
    %make_install
