name       : sayonara-player
version    : 1.7.0
release    : 10
source     :
    - https://sayonara-player.com/files/source/1.7.0-stable3/sayonara-player-1.7.0-stable3.tar.gz : 21c7ebe42a98e0bce324224236f5665eb19263a1f005c0e20be69d1ca8ef44a1
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small and fast audio player built with Qt
description: |
    Sayonara is a small, clear and fast audio player written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %patch -p1 < $pkgfiles/remove_wikia_lyrics_search.patch
    %cmake_ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
