name       : sayonara-player
version    : 0.9.3
release    : 3
source     :
    - http://sayonara-player.com/sw/sayonara-player-0.9.3-git2-20170509.tar.gz : 0412c6cf7e3d9283aa37caba08b009a9df6aeddb036cfca35af7dab40f5c14f5
license    : GPL-3.0
component  : multimedia.audio
summary    : A small, clear and fast audio player for Linux
description: |
    Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt
    framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(taglib)
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=true
build      : |
    %make
install    : |
    %make_install
