name       : sayonara-player
version    : 1.5.1
release    : 9
source     :
    - https://sayonara-player.com/sw/sayonara-player-1.5.1-stable5.tar.gz : f3f79cdc35d00e5f33aff2d480f2e03d49e51a83a233c8f45b357c29f38a747c
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small and fast audio player built with Qt
description: |
    Sayonara is a small, clear and fast audio player written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
