name       : sayonara-player
version    : 1.1.1
release    : 5
source     :
    - https://sayonara-player.com/sw/sayonara-player-1.1.1-git3-20180905.tar.gz : af8dd494f5df255a5cc18c0f35846a233fa6be9bc9f636dbbb1828f0b99742e9
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small, clear and fast audio player for Linux
description: |
    Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %cmake_ninja . -DBUILD_SHARED_LIBS=true
build      : |
    %ninja_build
install    : |
    %ninja_install
