name       : sayonara-player
version    : 1.3.0
release    : 6
source     :
    - https://sayonara-player.com/sw/sayonara-player-1.3.0-stable2-20190428.tar.gz : 5cc1a913aea27efeb3bdf9c6d90220446c8a6bb8c6ce67b9d30fd4e30928ea03
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small and fast audio player built with Qt
description: |
    Sayonara is a small, clear and fast audio player written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
